/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CourseJNI */

#ifndef _Included_CourseJNI
#define _Included_CourseJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CourseJNI
 * Method:    eligible
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_CourseJNI_eligible
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
